[package]
name = "zman"
version = "0.1.0"
edition = "2021"
description = "Manage Zig installations"

[dependencies]
clap = { version = "4.5.3", features = ["derive", "color", "wrap_help"] }
directories = "5.0.1"
duma = "0.2.0"
eyre = "0.6.12"
reqwest = { version = "0.12.1", features = ["blocking", "json"] }
semver = "1.0.22"
serde_json = "1.0.114"
tempfile = "3.10.1"

[profile.release]
opt-level = "z"
strip = true
lto = true
codegen-units = 1
panic = "abort"
